//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Funcionario.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Funcionario {
	public Object DadosPessoaisFuncionario;
	public Object FrequenciaFuncionario;
	public Object OcupacaoFuncionario;
	public Object HorarioPermitidoFuncionario;
}
