//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaEmail.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaEmail {
	public void EnviarEmail() {
	
	}
}
