//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.App_GlobalResources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso.
        /// </summary>
        public static string acesso {
            get {
                return ResourceManager.GetString("acesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso ao prédio.
        /// </summary>
        public static string acessoPredio {
            get {
                return ResourceManager.GetString("acessoPredio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradora.
        /// </summary>
        public static string administradora {
            get {
                return ResourceManager.GetString("administradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradoras.
        /// </summary>
        public static string administradoras {
            get {
                return ResourceManager.GetString("administradoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alocar.
        /// </summary>
        public static string alocar {
            get {
                return ResourceManager.GetString("alocar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alocar Pessoa em Moradia.
        /// </summary>
        public static string alocar_pessoa_moradia {
            get {
                return ResourceManager.GetString("alocar_pessoa_moradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andar.
        /// </summary>
        public static string andar {
            get {
                return ResourceManager.GetString("andar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        public static string apagar {
            get {
                return ResourceManager.GetString("apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Administradora.
        /// </summary>
        public static string apagarAdministradora {
            get {
                return ResourceManager.GetString("apagarAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Área pública.
        /// </summary>
        public static string apagarAreaPublica {
            get {
                return ResourceManager.GetString("apagarAreaPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Bloco.
        /// </summary>
        public static string apagarBloco {
            get {
                return ResourceManager.GetString("apagarBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Comentário.
        /// </summary>
        public static string apagarComentario {
            get {
                return ResourceManager.GetString("apagarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Condomínio.
        /// </summary>
        public static string apagarCondominio {
            get {
                return ResourceManager.GetString("apagarCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Enquete.
        /// </summary>
        public static string apagarEnquete {
            get {
                return ResourceManager.GetString("apagarEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Funcionário.
        /// </summary>
        public static string apagarFuncionario {
            get {
                return ResourceManager.GetString("apagarFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Grupo Plano de Contas.
        /// </summary>
        public static string apagarGrupoPlanoDeConta {
            get {
                return ResourceManager.GetString("apagarGrupoPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Pessoa.
        /// </summary>
        public static string apagarPessoa {
            get {
                return ResourceManager.GetString("apagarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Plano de Conta.
        /// </summary>
        public static string apagarPlanoDeConta {
            get {
                return ResourceManager.GetString("apagarPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Pontuação.
        /// </summary>
        public static string apagarPontuacao {
            get {
                return ResourceManager.GetString("apagarPontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Postagem.
        /// </summary>
        public static string apagarPostagem {
            get {
                return ResourceManager.GetString("apagarPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Reserva de Ambiente.
        /// </summary>
        public static string apagarReservaAmbiente {
            get {
                return ResourceManager.GetString("apagarReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Setor.
        /// </summary>
        public static string apagarSetor {
            get {
                return ResourceManager.GetString("apagarSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Veículo.
        /// </summary>
        public static string apagarVeiculo {
            get {
                return ResourceManager.GetString("apagarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apargar Condomínio.
        /// </summary>
        public static string apargarCondominio {
            get {
                return ResourceManager.GetString("apargarCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Registro de Ocorrência.
        /// </summary>
        public static string apargarRegistroOcorrencia {
            get {
                return ResourceManager.GetString("apargarRegistroOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Pública.
        /// </summary>
        public static string areaPublica {
            get {
                return ResourceManager.GetString("areaPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendimento.
        /// </summary>
        public static string atendimento {
            get {
                return ResourceManager.GetString("atendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo.
        /// </summary>
        public static string ativo {
            get {
                return ResourceManager.GetString("ativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string bairro {
            get {
                return ResourceManager.GetString("bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barulho.
        /// </summary>
        public static string Barulho {
            get {
                return ResourceManager.GetString("Barulho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloco.
        /// </summary>
        public static string bloco {
            get {
                return ResourceManager.GetString("bloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocos.
        /// </summary>
        public static string blocos {
            get {
                return ResourceManager.GetString("blocos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Requerido.
        /// </summary>
        public static string campo_requerido {
            get {
                return ResourceManager.GetString("campo_requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string cep {
            get {
                return ResourceManager.GetString("cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string cidade {
            get {
                return ResourceManager.GetString("cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string Cinco {
            get {
                return ResourceManager.GetString("Cinco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do morador.
        /// </summary>
        public static string codigoPessoa {
            get {
                return ResourceManager.GetString("codigoPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentar.
        /// </summary>
        public static string comentar {
            get {
                return ResourceManager.GetString("comentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário.
        /// </summary>
        public static string comentario {
            get {
                return ResourceManager.GetString("comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentarios.
        /// </summary>
        public static string comentarios {
            get {
                return ResourceManager.GetString("comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string complemento {
            get {
                return ResourceManager.GetString("complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condomínio.
        /// </summary>
        public static string condominio {
            get {
                return ResourceManager.GetString("condominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condomínios.
        /// </summary>
        public static string condominios {
            get {
                return ResourceManager.GetString("condominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar esta Administradora?.
        /// </summary>
        public static string confirmacaoApagarAdministradora {
            get {
                return ResourceManager.GetString("confirmacaoApagarAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você realmente deseja apagar essa enquete?.
        /// </summary>
        public static string confirmacaoApagarEnquete {
            get {
                return ResourceManager.GetString("confirmacaoApagarEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente Apagar Moradia.
        /// </summary>
        public static string confirmacaoApagarMoradia {
            get {
                return ResourceManager.GetString("confirmacaoApagarMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar esta pessoa?.
        /// </summary>
        public static string confirmacaoApagarPessoa {
            get {
                return ResourceManager.GetString("confirmacaoApagarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja remover esssa pontuação?.
        /// </summary>
        public static string confirmacaoApagarPontuacao {
            get {
                return ResourceManager.GetString("confirmacaoApagarPontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja cancelar esta reserva?.
        /// </summary>
        public static string confirmacaoApagarReserva {
            get {
                return ResourceManager.GetString("confirmacaoApagarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este veículo?.
        /// </summary>
        public static string confirmacaoApagarVeiculo {
            get {
                return ResourceManager.GetString("confirmacaoApagarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este bloco?.
        /// </summary>
        public static string confirmacaoBloco {
            get {
                return ResourceManager.GetString("confirmacaoBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este condominio?.
        /// </summary>
        public static string confirmacaoCondominio {
            get {
                return ResourceManager.GetString("confirmacaoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este funcionário?.
        /// </summary>
        public static string confirmacaoFuncionario {
            get {
                return ResourceManager.GetString("confirmacaoFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar esse grupo plano de conta?.
        /// </summary>
        public static string confirmacaoGrupoPlanoDeConta {
            get {
                return ResourceManager.GetString("confirmacaoGrupoPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar o Plano de Conta?.
        /// </summary>
        public static string confirmacaoPlanoDeConta {
            get {
                return ResourceManager.GetString("confirmacaoPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este setor?.
        /// </summary>
        public static string confirmacaoSetor {
            get {
                return ResourceManager.GetString("confirmacaoSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmaNovaSenha.
        /// </summary>
        public static string confirmaNovaSenha {
            get {
                return ResourceManager.GetString("confirmaNovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme o E-mail.
        /// </summary>
        public static string confirmarEmail {
            get {
                return ResourceManager.GetString("confirmarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma Senha.
        /// </summary>
        public static string confirmaSenha {
            get {
                return ResourceManager.GetString("confirmaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme a Senha.
        /// </summary>
        public static string confirmeSenha {
            get {
                return ResourceManager.GetString("confirmeSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cor.
        /// </summary>
        public static string cor {
            get {
                return ResourceManager.GetString("cor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string cpf {
            get {
                return ResourceManager.GetString("cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criador.
        /// </summary>
        public static string criador {
            get {
                return ResourceManager.GetString("criador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dano ao Patrimônio.
        /// </summary>
        public static string DanoAoPatrimonio {
            get {
                return ResourceManager.GetString("DanoAoPatrimonio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Publicação Automática.
        /// </summary>
        public static string dataAutomatica {
            get {
                return ResourceManager.GetString("dataAutomatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entrada.
        /// </summary>
        public static string dataEntrada {
            get {
                return ResourceManager.GetString("dataEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Exclusão Automática.
        /// </summary>
        public static string dataExclusao {
            get {
                return ResourceManager.GetString("dataExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Finalização.
        /// </summary>
        public static string dataFim {
            get {
                return ResourceManager.GetString("dataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de fechamento da enquete.
        /// </summary>
        public static string dataFimEnquete {
            get {
                return ResourceManager.GetString("dataFimEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Início.
        /// </summary>
        public static string dataInicio {
            get {
                return ResourceManager.GetString("dataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de abertura da enquete.
        /// </summary>
        public static string dataInicioEnquete {
            get {
                return ResourceManager.GetString("dataInicioEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Publicação.
        /// </summary>
        public static string dataPublicacao {
            get {
                return ResourceManager.GetString("dataPublicacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saida.
        /// </summary>
        public static string dataSaida {
            get {
                return ResourceManager.GetString("dataSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string descricao {
            get {
                return ResourceManager.GetString("descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do Grupo de Plano de Contas.
        /// </summary>
        public static string descricaoGrupoPlanoContas {
            get {
                return ResourceManager.GetString("descricaoGrupoPlanoContas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do Plano de Conta.
        /// </summary>
        public static string descricaoPlanoDeConta {
            get {
                return ResourceManager.GetString("descricaoPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string detalhes {
            get {
                return ResourceManager.GetString("detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes Administradora.
        /// </summary>
        public static string detalhesAdministradora {
            get {
                return ResourceManager.GetString("detalhesAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Bloco.
        /// </summary>
        public static string detalhesBloco {
            get {
                return ResourceManager.GetString("detalhesBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Comentário.
        /// </summary>
        public static string detalhesComentario {
            get {
                return ResourceManager.GetString("detalhesComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Condomínio.
        /// </summary>
        public static string detalhesCondominio {
            get {
                return ResourceManager.GetString("detalhesCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Enquete.
        /// </summary>
        public static string detalhesEnquete {
            get {
                return ResourceManager.GetString("detalhesEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Funcionário.
        /// </summary>
        public static string detalhesFuncionario {
            get {
                return ResourceManager.GetString("detalhesFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Grupo Plano de Contas.
        /// </summary>
        public static string detalhesGrupoPlanoDeContas {
            get {
                return ResourceManager.GetString("detalhesGrupoPlanoDeContas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes Pessoa.
        /// </summary>
        public static string detalhesPessoa {
            get {
                return ResourceManager.GetString("detalhesPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Plano de Conta.
        /// </summary>
        public static string detalhesPlanoDeConta {
            get {
                return ResourceManager.GetString("detalhesPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Pontuação.
        /// </summary>
        public static string detalhesPontuacao {
            get {
                return ResourceManager.GetString("detalhesPontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Postagem.
        /// </summary>
        public static string detalhesPostagem {
            get {
                return ResourceManager.GetString("detalhesPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Reserva de Ambiente.
        /// </summary>
        public static string detalhesReservaAmbiente {
            get {
                return ResourceManager.GetString("detalhesReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Setor.
        /// </summary>
        public static string detalhesSetor {
            get {
                return ResourceManager.GetString("detalhesSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Veículo.
        /// </summary>
        public static string detalhesVeiculo {
            get {
                return ResourceManager.GetString("detalhesVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        public static string Dez {
            get {
                return ResourceManager.GetString("Dez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Dois {
            get {
                return ResourceManager.GetString("Dois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Administradora.
        /// </summary>
        public static string editarAdministradora {
            get {
                return ResourceManager.GetString("editarAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Bloco.
        /// </summary>
        public static string editarBloco {
            get {
                return ResourceManager.GetString("editarBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Comentário.
        /// </summary>
        public static string editarComentario {
            get {
                return ResourceManager.GetString("editarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Condomínio.
        /// </summary>
        public static string editarCondominio {
            get {
                return ResourceManager.GetString("editarCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar a Enquete.
        /// </summary>
        public static string editarEnquete {
            get {
                return ResourceManager.GetString("editarEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Funcionário.
        /// </summary>
        public static string editarFuncionario {
            get {
                return ResourceManager.GetString("editarFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Grupo Plano de Contas.
        /// </summary>
        public static string editarGrupoPlanoDeContas {
            get {
                return ResourceManager.GetString("editarGrupoPlanoDeContas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pessoa.
        /// </summary>
        public static string editarPessoa {
            get {
                return ResourceManager.GetString("editarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Plano de Conta.
        /// </summary>
        public static string editarPlanoDeConta {
            get {
                return ResourceManager.GetString("editarPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pontuação.
        /// </summary>
        public static string editarPontuacao {
            get {
                return ResourceManager.GetString("editarPontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Postagem.
        /// </summary>
        public static string editarPostagem {
            get {
                return ResourceManager.GetString("editarPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proprietário.
        /// </summary>
        public static string editarProprietario {
            get {
                return ResourceManager.GetString("editarProprietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Reserva de Ambiente.
        /// </summary>
        public static string editarReservaAmbiente {
            get {
                return ResourceManager.GetString("editarReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Setor.
        /// </summary>
        public static string editarSetor {
            get {
                return ResourceManager.GetString("editarSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Veículo.
        /// </summary>
        public static string editarVeiculo {
            get {
                return ResourceManager.GetString("editarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Inválido.
        /// </summary>
        public static string email_invalido {
            get {
                return ResourceManager.GetString("email_invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os E-mail não coincidem.
        /// </summary>
        public static string emailNaoCoincidem {
            get {
                return ResourceManager.GetString("emailNaoCoincidem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Análise.
        /// </summary>
        public static string EmAnalise {
            get {
                return ResourceManager.GetString("EmAnalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Em Execução.
        /// </summary>
        public static string EmExecucao {
            get {
                return ResourceManager.GetString("EmExecucao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço de E-mail.
        /// </summary>
        public static string enderecoEmail {
            get {
                return ResourceManager.GetString("enderecoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquete.
        /// </summary>
        public static string enquete {
            get {
                return ResourceManager.GetString("enquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes.
        /// </summary>
        public static string enquetes {
            get {
                return ResourceManager.GetString("enquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes Ativas.
        /// </summary>
        public static string enquetesAtivas {
            get {
                return ResourceManager.GetString("enquetesAtivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes em Andamento.
        /// </summary>
        public static string enquetesEmAndamento {
            get {
                return ResourceManager.GetString("enquetesEmAndamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes Finalizadas.
        /// </summary>
        public static string enquetesFinalizadas {
            get {
                return ResourceManager.GetString("enquetesFinalizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalizada.
        /// </summary>
        public static string Finalizada {
            get {
                return ResourceManager.GetString("Finalizada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequência.
        /// </summary>
        public static string frequencia {
            get {
                return ResourceManager.GetString("frequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        public static string funcionario {
            get {
                return ResourceManager.GetString("funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionários.
        /// </summary>
        public static string funcionarios {
            get {
                return ResourceManager.GetString("funcionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Plano de Conta.
        /// </summary>
        public static string grupoPlanoDeConta {
            get {
                return ResourceManager.GetString("grupoPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo Plano de Contas.
        /// </summary>
        public static string grupoPlanoDeContas {
            get {
                return ResourceManager.GetString("grupoPlanoDeContas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horário Permitido.
        /// </summary>
        public static string horarioPermitido {
            get {
                return ResourceManager.GetString("horarioPermitido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Área Pública.
        /// </summary>
        public static string idArea {
            get {
                return ResourceManager.GetString("idArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do condomínio.
        /// </summary>
        public static string idCondominio {
            get {
                return ResourceManager.GetString("idCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Pessoa.
        /// </summary>
        public static string idPessoa {
            get {
                return ResourceManager.GetString("idPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do síndico.
        /// </summary>
        public static string idSindico {
            get {
                return ResourceManager.GetString("idSindico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Status Pagamento.
        /// </summary>
        public static string idStatusPagamento {
            get {
                return ResourceManager.GetString("idStatusPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Tipo Moradia.
        /// </summary>
        public static string idTipoMoradia {
            get {
                return ResourceManager.GetString("idTipoMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Veículo.
        /// </summary>
        public static string idVeiculo {
            get {
                return ResourceManager.GetString("idVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista das Áreas públicas.
        /// </summary>
        public static string listaAreasPublicas {
            get {
                return ResourceManager.GetString("listaAreasPublicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Registros de Ocorrência.
        /// </summary>
        public static string listaRegistroOcorrencia {
            get {
                return ResourceManager.GetString("listaRegistroOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenha-me conectado.
        /// </summary>
        public static string manterConectado {
            get {
                return ResourceManager.GetString("manterConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Comentários.
        /// </summary>
        public static string meusComentarios {
            get {
                return ResourceManager.GetString("meusComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minhas Postagens.
        /// </summary>
        public static string minhasPostagens {
            get {
                return ResourceManager.GetString("minhasPostagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string modelo {
            get {
                return ResourceManager.GetString("modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moradia.
        /// </summary>
        public static string moradia {
            get {
                return ResourceManager.GetString("moradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Administradora.
        /// </summary>
        public static string nome_adm {
            get {
                return ResourceManager.GetString("nome_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Pessoa.
        /// </summary>
        public static string nome_pessoa {
            get {
                return ResourceManager.GetString("nome_pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Pessoa.
        /// </summary>
        public static string nomePessoa {
            get {
                return ResourceManager.GetString("nomePessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Setor.
        /// </summary>
        public static string nomeSetor {
            get {
                return ResourceManager.GetString("nomeSetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Usuário.
        /// </summary>
        public static string nomeUsuario {
            get {
                return ResourceManager.GetString("nomeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Administradora.
        /// </summary>
        public static string novaAdministradora {
            get {
                return ResourceManager.GetString("novaAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Área Pública.
        /// </summary>
        public static string novaArea {
            get {
                return ResourceManager.GetString("novaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Enquete.
        /// </summary>
        public static string novaEnquete {
            get {
                return ResourceManager.GetString("novaEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Moradia.
        /// </summary>
        public static string novaMoradia {
            get {
                return ResourceManager.GetString("novaMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Pessoa.
        /// </summary>
        public static string novaPessoa {
            get {
                return ResourceManager.GetString("novaPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Pontuação.
        /// </summary>
        public static string novaPontuacao {
            get {
                return ResourceManager.GetString("novaPontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Postagem.
        /// </summary>
        public static string novaPostagem {
            get {
                return ResourceManager.GetString("novaPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Reserva de Ambiente.
        /// </summary>
        public static string novaReservaAmbiente {
            get {
                return ResourceManager.GetString("novaReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string novaSenha {
            get {
                return ResourceManager.GetString("novaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        public static string Nove {
            get {
                return ResourceManager.GetString("Nove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string novo {
            get {
                return ResourceManager.GetString("novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Condomínio.
        /// </summary>
        public static string novoCondominio {
            get {
                return ResourceManager.GetString("novoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo registro de acesso.
        /// </summary>
        public static string novoRegistroAcesso {
            get {
                return ResourceManager.GetString("novoRegistroAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Registro de Ocorrência.
        /// </summary>
        public static string novoRegistroOcorrencia {
            get {
                return ResourceManager.GetString("novoRegistroOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Veículo.
        /// </summary>
        public static string novoVeiculo {
            get {
                return ResourceManager.GetString("novoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupação.
        /// </summary>
        public static string ocupacao {
            get {
                return ResourceManager.GetString("ocupacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string Oito {
            get {
                return ResourceManager.GetString("Oito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opções.
        /// </summary>
        public static string opcoes {
            get {
                return ResourceManager.GetString("opcoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros.
        /// </summary>
        public static string Outros {
            get {
                return ResourceManager.GetString("Outros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outros Tipos de Ocorrência.
        /// </summary>
        public static string outros_tipos_ocorrencia {
            get {
                return ResourceManager.GetString("outros_tipos_ocorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está seguro que quer fazer isso?.
        /// </summary>
        public static string perguntaConfirmacao {
            get {
                return ResourceManager.GetString("perguntaConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa.
        /// </summary>
        public static string pessoa {
            get {
                return ResourceManager.GetString("pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas.
        /// </summary>
        public static string pessoas {
            get {
                return ResourceManager.GetString("pessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa.
        /// </summary>
        public static string placa {
            get {
                return ResourceManager.GetString("placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano de Conta.
        /// </summary>
        public static string planoDeConta {
            get {
                return ResourceManager.GetString("planoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuação.
        /// </summary>
        public static string pontuacao {
            get {
                return ResourceManager.GetString("pontuacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuações.
        /// </summary>
        public static string pontuacoes {
            get {
                return ResourceManager.GetString("pontuacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuar.
        /// </summary>
        public static string pontuar {
            get {
                return ResourceManager.GetString("pontuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontuar Pessoa.
        /// </summary>
        public static string pontuarPessoa {
            get {
                return ResourceManager.GetString("pontuarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postagem.
        /// </summary>
        public static string postagem {
            get {
                return ResourceManager.GetString("postagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postagens.
        /// </summary>
        public static string postagens {
            get {
                return ResourceManager.GetString("postagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predio.
        /// </summary>
        public static string predio {
            get {
                return ResourceManager.GetString("predio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprietário.
        /// </summary>
        public static string proprietario {
            get {
                return ResourceManager.GetString("proprietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Andares.
        /// </summary>
        public static string qtdeAndares {
            get {
                return ResourceManager.GetString("qtdeAndares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Moradias.
        /// </summary>
        public static string qtdeMoradias {
            get {
                return ResourceManager.GetString("qtdeMoradias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string Quatro {
            get {
                return ResourceManager.GetString("Quatro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar acesso.
        /// </summary>
        public static string registrarAcesso {
            get {
                return ResourceManager.GetString("registrarAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo é obrigatório!.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva de Ambiente.
        /// </summary>
        public static string reservaAmbiente {
            get {
                return ResourceManager.GetString("reservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservas de Ambiente.
        /// </summary>
        public static string reservasAmbiente {
            get {
                return ResourceManager.GetString("reservasAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolvido.
        /// </summary>
        public static string Resolvido {
            get {
                return ResourceManager.GetString("Resolvido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string rg {
            get {
                return ResourceManager.GetString("rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roubo.
        /// </summary>
        public static string Roubo {
            get {
                return ResourceManager.GetString("Roubo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolvida.
        /// </summary>
        public static string Rresolvida {
            get {
                return ResourceManager.GetString("Rresolvida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua.
        /// </summary>
        public static string rua {
            get {
                return ResourceManager.GetString("rua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string salvar {
            get {
                return ResourceManager.GetString("salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string Seis {
            get {
                return ResourceManager.GetString("Seis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string selecione {
            get {
                return ResourceManager.GetString("selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string senhaAtual {
            get {
                return ResourceManager.GetString("senhaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha e a confirmação da senha não coincidem.
        /// </summary>
        public static string senhaConfSenhaNaoCoincidem {
            get {
                return ResourceManager.GetString("senhaConfSenhaNaoCoincidem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Curta.
        /// </summary>
        public static string senhaCurta {
            get {
                return ResourceManager.GetString("senhaCurta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string Sete {
            get {
                return ResourceManager.GetString("Sete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setor.
        /// </summary>
        public static string setor {
            get {
                return ResourceManager.GetString("setor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Síndico.
        /// </summary>
        public static string sindico {
            get {
                return ResourceManager.GetString("sindico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Atentimento.
        /// </summary>
        public static string status_atentimento {
            get {
                return ResourceManager.GetString("status_atentimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Ocorrência.
        /// </summary>
        public static string status_ocorrencia {
            get {
                return ResourceManager.GetString("status_ocorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status da Enquente.
        /// </summary>
        public static string statusEnquente {
            get {
                return ResourceManager.GetString("statusEnquente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status do Pagamento.
        /// </summary>
        public static string statusPagamento {
            get {
                return ResourceManager.GetString("statusPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        public static string tamanho {
            get {
                return ResourceManager.GetString("tamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone Celular.
        /// </summary>
        public static string telefoneCelular {
            get {
                return ResourceManager.GetString("telefoneCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone Fixo.
        /// </summary>
        public static string telefoneFixo {
            get {
                return ResourceManager.GetString("telefoneFixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Ocorrência.
        /// </summary>
        public static string tipo_ocorrencia {
            get {
                return ResourceManager.GetString("tipo_ocorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Moradia.
        /// </summary>
        public static string tipoMoradia {
            get {
                return ResourceManager.GetString("tipoMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do Plano de Conta.
        /// </summary>
        public static string tipoPlanoDeConta {
            get {
                return ResourceManager.GetString("tipoPlanoDeConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do veículo.
        /// </summary>
        public static string tipoVeiculo {
            get {
                return ResourceManager.GetString("tipoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da Postagem.
        /// </summary>
        public static string tituloPostagem {
            get {
                return ResourceManager.GetString("tituloPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas Enquetes.
        /// </summary>
        public static string todasEnquetes {
            get {
                return ResourceManager.GetString("todasEnquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string Tres {
            get {
                return ResourceManager.GetString("Tres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Um {
            get {
                return ResourceManager.GetString("Um", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Pagamento.
        /// </summary>
        public static string valorPagamento {
            get {
                return ResourceManager.GetString("valorPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo.
        /// </summary>
        public static string veiculo {
            get {
                return ResourceManager.GetString("veiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículos.
        /// </summary>
        public static string veiculos {
            get {
                return ResourceManager.GetString("veiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Comentários.
        /// </summary>
        public static string visualizarComentarios {
            get {
                return ResourceManager.GetString("visualizarComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Pontuações.
        /// </summary>
        public static string visualizarPontuacoes {
            get {
                return ResourceManager.GetString("visualizarPontuacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string voltar {
            get {
                return ResourceManager.GetString("voltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
