//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorGerenciarEspacos.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorGerenciarEspacos {
	public void AlterarStatusAreaPublica() {
	
	}
	
	public void NovaAreaPublica() {
	
	}
	
	public void Validar() {
	
	}
	
	public void NovaMoradia() {
	
	}
	
	public void NovoBloco() {
	
	}
	
	public void VisualizarDadosBloco() {
	
	}
	
	public void EditarDadosBloco() {
	
	}
	
	public void ValidarDados() {
	
	}
	
	public void ExcluirBloco() {
	
	}
	
	public void Autenticar() {
	
	}
	
	public void VisualizarDadosMoradia() {
	
	}
	
	public void EditarDadosMoradia() {
	
	}
	
	public void ExcluirMoradia() {
	
	}
	
	public void NovaAreaPublica() {
	
	}
	
	public void ExcluirAreaPublica() {
	
	}
	
	public void EditarAreaPublica() {
	
	}
	
	public void AlterarStatusAreaPublica() {
	
	}
}
