//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorPublicarNoMural.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorPublicarNoMural {
	public void NovaPublicacaoMural() {
	
	}
	
	public void ValidarDados() {
	
	}
	
	public void VisualizarPublicacaoMural() {
	
	}
	
	public void EditarPublicacaoMural() {
	
	}
	
	public void EditarPublicacaoMural() {
	
	}
	
	public void Autenticar() {
	
	}
}
