//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorReceitasDespesas.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorReceitasDespesas {
}
