//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ocorrencia.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Ocorrencia {
	public Object MoradorCriadorOcorrencia;
	public Object TituloOcorrencia;
	public Object DescricaoOcorrencia;
	public Object DataCriacaoOcorrencia;
	public Object EstadoOcorrencia;
}
