//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaCondominio.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaCondominio {
	public void NovoCondominio() {
	
	}
	
	public void VisualizarDadosCondominio() {
	
	}
	
	public void EditarDadosCondominio() {
	
	}
	
	public void ExcluirCondominio() {
	
	}
	
	public void SalvarDadosCondominio() {
	
	}
}
