//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaAtendimento.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaAtendimento {
	public void ResponderMensagem() {
	
	}
	
	public void SalvareEnviarMensagem() {
	
	}
	
	public void EnviarMensagem() {
	
	}
	
	public void MarcarStatusMensagem() {
	
	}
}
