//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaPlanoDeConta.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaPlanoDeConta {
	public void NovoPlanoDeConta() {
	
	}
	
	public void VisualizarDadosPlanoDeConta() {
	
	}
	
	public void EditarDadosPlanoDeConta() {
	
	}
	
	public void ExcluirPlanoDeConta() {
	
	}
	
	public void SalvarDadosPlanoDeConta() {
	
	}
}
