//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PublicacaoMuralEletronico.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PublicacaoMuralEletronico {
	public Object AutorPublicacao;
	public Object TituloPublicacao;
	public Object DescricaoPublicacao;
	public Object DataParaPublicacao;
	public Object DataParaExclusaoPublicacao;
}
