//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sindico.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Sindico {
	public Object DadosPessoaisSindico;
}
