//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaEnquetes.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaEnquetes {
	public void VisualizarEnquete() {
	
	}
}
