//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarReservas.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarReservas {
	public void AnalisarReservaAmbiente() {
	
	}
	
	public void VisualizarReservas() {
	
	}
}
