//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Autenticacao.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Autenticacao {
}
