//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorGerenciarProprietario.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorGerenciarProprietario {
	public void CadastrarProprietario() {
	
	}
	
	public void AnalisarDados() {
	
	}
	
	public void VisualizarDadosProprietario() {
	
	}
	
	public void EditarDadosProprietario() {
	
	}
	
	public void ExcluirProprietario() {
	
	}
	
	public void Autenticar() {
	
	}
}
