//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorGerenciarVeículo.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorGerenciarVeículo {
	public void NovoVeiculo() {
	
	}
	
	public void AnalisarDados() {
	
	}
	
	public void VisualizarDadosVeiculo() {
	
	}
	
	public void VisualizarDadosVeiculo() {
	
	}
	
	public void VisualizarDadosVeiculo() {
	
	}
	
	public void ExcluirVeiculo() {
	
	}
	
	public void Autenticar() {
	
	}
}
