//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorPessoa.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorPessoa {
	public void BuscarPessoa() {
	
	}
	
	public void AnalisarResultadoBusca() {
	
	}
	
	public void NovaPessoa() {
	
	}
	
	public void AnalisarDados() {
	
	}
	
	public void EditarDadosPessoa() {
	
	}
	
	public void ExcluirPessoa() {
	
	}
	
	public void Autenticar() {
	
	}
	
	public void BuscarPessoa() {
	
	}
	
	public void BuscarDadosPessoa() {
	
	}
}
