//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaMoradia.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaMoradia {
	public void NovaMoradia() {
	
	}
	
	public void VisualizarDadosMoradia() {
	
	}
	
	public void EditarDadosMoradia() {
	
	}
	
	public void ExcluirMoradia() {
	
	}
	
	public void SalvarDadosMoradia() {
	
	}
}
