//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarAreasPublicas.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarAreasPublicas {
	public void NovaAreaPublica() {
	
	}
	
	public void ExcluirAreaPublica() {
	
	}
	
	public void EditarAreaPublica() {
	
	}
	
	public void AlterarStatusAreaPublica() {
	
	}
}
