//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarEmail.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarEmail {
	public void EnviarEmail() {
	
	}
	
	public void EscreverEmail() {
	
	}
	
	public void VisualizarEmail() {
	
	}
}
