//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorEnquete.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorEnquete {
	public void VerificarSeJaVotou() {
	
	}
	
	public void VotarEnquete() {
	
	}
	
	public void VisualizarEnquete() {
	
	}
}
