//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarFuncionarios.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarFuncionarios {
	public void NovoFuncionario() {
	
	}
	
	public void NovoSetor() {
	
	}
	
	public void ExcluirSetor() {
	
	}
	
	public void EditarSetor() {
	
	}
	
	public void EditarDadosFuncionario() {
	
	}
	
	public void VisualizarDadosFuncionario() {
	
	}
	
	public void ExcluirFuncionario() {
	
	}
}
