//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarEnquetes.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarEnquetes {
	public void NovaEnquete() {
	
	}
	
	public void VisualizarEnquetes() {
	
	}
	
	public void ExcluirEnquete() {
	
	}
}
