//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarCadastroDeProprietario.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarCadastroDeProprietario {
	public void CadastrarProprietario() {
	
	}
	
	public void VisualizarDadosProprietario() {
	
	}
	
	public void EditarDadosProprietario() {
	
	}
	
	public void ExcluirProprietario() {
	
	}
}
