//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorAutenticar.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorAutenticar {
	public void CompararDados() {
	
	}
	
	public void AnalisarDados() {
	
	}
	
	public void ValidarLoginSenha() {
	
	}
	
	public void InserirDadosDeAcesso() {
	
	}
	
	public void RecuperarLoginSenha() {
	
	}
}
