//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaVeiculo.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaVeiculo {
	public void NovoVeiculo() {
	
	}
	
	public void VisualizarDadosVeiculo() {
	
	}
	
	public void EditarDadosVeiculo() {
	
	}
	
	public void SalvarDadosVeiculo() {
	
	}
	
	public void ExcluirVeiculo() {
	
	}
}
