//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaAreaPublica.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaAreaPublica {
	public void NovaAreaPublica() {
	
	}
	
	public void VisualizarDadosAreaPublica() {
	
	}
	
	public void EditarDadosAreaPublica() {
	
	}
	
	public void ExcluirAreaPublica() {
	
	}
	
	public void SalvarDadosAreaPublica() {
	
	}
}
