//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReservaAmbiente.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ReservaAmbiente {
	public Object MoradorReserva;
	public Object AreaReserva;
	public Object DataInicioReserva;
	public Object DataFimReserva;
	public Object HoraInicioReserva;
	public Object HoraFimReserva;
	public Object PagamentoReserva;
}
