//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Setor.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Setor {
	public Object NomeSetor;
	public Object DescricaoSetor;
}
