//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaAutenticar.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaAutenticar {
	public void InserirDadosDeAcesso() {
	
	}
	
	public void RecuperarLoginSenha() {
	
	}
}
