//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorListaDiscussao.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorListaDiscussao {
	public void Comentar() {
	
	}
	
	public void EnviarComentario() {
	
	}
	
	public void ValidarComentario() {
	
	}
	
	public void NovaLista() {
	
	}
	
	public void ValidarDados() {
	
	}
	
	public void VisualisarListaDeDiscussao() {
	
	}
	
	public void ExcluirListaDeDiscussao() {
	
	}
	
	public void AnalisarCriadorLista() {
	
	}
	
	public void Autenticar() {
	
	}
}
