//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorGerenciarCondominios.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorGerenciarCondominios {
	public void NovoCondominio() {
	
	}
	
	public void Validar()() {
	
	}
	
	public void EditarDadosCondominio() {
	
	}
	
	public void Validar() {
	
	}
	
	public void Autenticar() {
	
	}
	
	public void ExcluirCondominio() {
	
	}
	
	public void VisualizarDadosCondominio() {
	
	}
	
	public void ExibirDadosCondominio() {
	
	}
}
