//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorGerenciarEnquete.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorGerenciarEnquete {
	public void NovaEnquete() {
	
	}
	
	public void ValidarDados() {
	
	}
	
	public void VisualizarEnquetes() {
	
	}
	
	public void VisualizarEnquetes() {
	
	}
	
	public void ExcluirEnquete() {
	
	}
	
	public void Autenticar() {
	
	}
}
