//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MovimentacaoFinanceira.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class MovimentacaoFinanceira {
	public Object DescricaoMovimentacao;
	public Object ValorMovimentacao;
	public Object DataRegistroMovimentacao;
	public Object SituacaoMovimentacao;
	public Object TipoMovimentacao;
	public Object CompetenciaMovimentacao;
}
