//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaMovimentacaoFinanceira.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaMovimentacaoFinanceira {
	public void GerarPDF() {
	
	}
	
	public void PublicarFinancas() {
	
	}
	
	public void SalvarRascunho() {
	
	}
	
	public void HistoricoDeAlteracoes() {
	
	}
}
