//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaProprietario.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaProprietario {
	public void NovoProprietario() {
	
	}
	
	public void VisualizarDadosProprietario() {
	
	}
	
	public void EditarDadosProprietario() {
	
	}
	
	public void ExcluirProprietario() {
	
	}
	
	public void SalvarDadosProprietario() {
	
	}
}
