//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaRegistrarOcorrencia.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaRegistrarOcorrencia {
	public void NovaOcorrencia() {
	
	}
	
	public void VisualizarOcorrencia() {
	
	}
	
	public void EditarOcorrencia() {
	
	}
	
	public void ExcluirOcorrencia() {
	
	}
}
