//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaReservarAmbientes.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaReservarAmbientes {
	public void VerificarPossibilidadeDeReserva() {
	
	}
	
	public void NovaReservaAmbiente() {
	
	}
	
	public void VisualisarDadosReserva() {
	
	}
	
	public void EditarDadosReserva() {
	
	}
	
	public void ExcluirReserva() {
	
	}
}
