//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarCentralDeAtendimento.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarCentralDeAtendimento {
	public void ResponderMensagem() {
	
	}
	
	public void ExibirPerguntaseRespostasFrequentes() {
	
	}
	
	public void VisualizarRespostaRapida() {
	
	}
	
	public void VisualizarMensagem() {
	
	}
}
