//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaMuralEletronico.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaMuralEletronico {
	public void NovaPublicacaoMural() {
	
	}
	
	public void VisualizarPublicacaoMural() {
	
	}
	
	public void EditarPublicacaoMural() {
	
	}
	
	public void ExcluirPublicacaoMural() {
	
	}
}
