//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Veiculo.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Veiculo {
	public Object ProprietarioVeiculo;
	public Object PlacaVeiculo;
	public Object ModeloVeiculo;
	public Object CorVeiculo;
	public Object TipoVeiculo;
}
