//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bloco.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Bloco {
	public Object NomeBloco;
	public Object QuantidadeAndares;
}
