//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorOcorrencia.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorOcorrencia {
	public void NovaOcorrencia() {
	
	}
	
	public void ValidarDados() {
	
	}
	
	public void AlterarStatusOcorrencia() {
	
	}
	
	public void VisualizarOcorrencia() {
	
	}
	
	public void EditarOcorrencia() {
	
	}
	
	public void ExcluirOcorrencia() {
	
	}
	
	public void Autenticar() {
	
	}
	
	public void NovoTipoOcorrencia() {
	
	}
}
