//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorReservaAmbiente.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorReservaAmbiente {
	public void VerificarQuantidadeDeReservas() {
	
	}
	
	public void NovaReservaAmbiente() {
	
	}
	
	public void AnalisarReservaAmbiente() {
	
	}
	
	public void VisualisarDadosReserva() {
	
	}
	
	public void EditarDadosReserva() {
	
	}
	
	public void AnalisarDados() {
	
	}
	
	public void ExcluirReserva() {
	
	}
	
	public void Autenticar() {
	
	}
	
	public void VisualizarReserva() {
	
	}
}
