//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Moradia.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Moradia {
	public Object ProprietarioMoradia;
	public Object Responsavel;
	public Object Predio;
	public Object Andar;
	public Object Numero;
	public Object Tipo;
}
