//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaMuralEletronico.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaMuralEletronico {
	public void NovoAvisoMural() {
	
	}
	
	public void EditarDadosAviso() {
	
	}
	
	public void SalvarDadosAviso() {
	
	}
	
	public void VisualizarDadosAviso() {
	
	}
	
	public void ExcluirAviso() {
	
	}
}
