//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarCondominios.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarCondominios implements Condominio {
	public void NovoCondominio() {
	
	}
	
	public void EditarDadosCondominio() {
	
	}
	
	public void ExcluirCondominio() {
	
	}
	
	public void VisualizarDadosCondominio() {
	
	}
}
