//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enquete.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Enquete {
	public Object TituloEnquete;
	public Object DescricaoEnquete;
	public Object OpcoesEnquete;
	public Object DataInicioEnquete;
	public Object DataFimEnquete;
	public Object StatusEnquete;
}
