//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ListaDeDiscussao.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ListaDeDiscussao {
	public Object CriadorLista;
	public Object TituloLista;
	public Object DescicaoLista;
	public Object DataCriacaoLista;
}
