//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaAmbiente.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaAmbiente {
	public void NovaReservaAmbiente() {
	
	}
	
	public void VisualizarDadosReservaAmbiente() {
	
	}
	
	public void EnviarComprovantePagamento() {
	
	}
	
	public void EditarDadosReservaAmbiente() {
	
	}
	
	public void SalvarDadosReservaAmbiente() {
	
	}
	
	public void ExcluirReservaAmbiente() {
	
	}
	
	public void MarcarStatusReserva() {
	
	}
}
