//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaEnquete.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaEnquete {
	public void EnviarVotoEnquete() {
	
	}
	
	public void NovaEnquete() {
	
	}
	
	public void MarcarStatusEnquete() {
	
	}
	
	public void SalvarDadosEnquete() {
	
	}
	
	public void ExcluirEnquete() {
	
	}
}
