//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PontuacaoFuncionario.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PontuacaoFuncionario {
	public Object Funcionario;
	public Object Area;
	public Object Pontuacao;
}
