//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarListasDeDiscussão.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarListasDeDiscussão {
	public void Comentar() {
	
	}
	
	public void EnviarComentario() {
	
	}
	
	public void NovaLista() {
	
	}
	
	public void VisualisarListaDeDiscussao() {
	
	}
	
	public void ExcluirListaDeDiscussao() {
	
	}
}
