//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaBloco.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaBloco {
	public void NovoBloco() {
	
	}
	
	public void VisualizarDadosBloco() {
	
	}
	
	public void EditarDadosBloco() {
	
	}
	
	public void ExcluirBloco() {
	
	}
	
	public void SalvarDadosBloco() {
	
	}
}
