//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Proprietario.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Proprietario {
	public Object DadosPessoaisProprietario;
	public Object EnderecoProprietario;
}
