//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VotoEnquete.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class VotoEnquete {
	public Object Morador;
	public Object Enquete;
	public Object VotoEnquete;
}
