INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('1', '1', 'Morador');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('2', '1', 'Sindico');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('3', '1', 'Visitante');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('4', '1', 'Administradora');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('5', '1', 'Proprietario');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('6', '1', 'Funcionario');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('7', '1', 'Responsavel');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('8', '1', 'Profissional');
INSERT INTO `residentialbd`.`my_aspnet_roles` (`id`, `applicationId`, `name`) VALUES ('9', '1', 'AdministradorSistema');