//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.App_GlobalResources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradora.
        /// </summary>
        public static string administradora {
            get {
                return ResourceManager.GetString("administradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administradoras.
        /// </summary>
        public static string administradoras {
            get {
                return ResourceManager.GetString("administradoras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andar.
        /// </summary>
        public static string andar {
            get {
                return ResourceManager.GetString("andar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar.
        /// </summary>
        public static string apagar {
            get {
                return ResourceManager.GetString("apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Administradora.
        /// </summary>
        public static string apagarAdministradora {
            get {
                return ResourceManager.GetString("apagarAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Área pública.
        /// </summary>
        public static string apagarAreaPublica {
            get {
                return ResourceManager.GetString("apagarAreaPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Bloco.
        /// </summary>
        public static string apagarBloco {
            get {
                return ResourceManager.GetString("apagarBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Condomínio.
        /// </summary>
        public static string apagarCondominio {
            get {
                return ResourceManager.GetString("apagarCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Enquete.
        /// </summary>
        public static string apagarEnquete {
            get {
                return ResourceManager.GetString("apagarEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Pessoa.
        /// </summary>
        public static string apagarPessoa {
            get {
                return ResourceManager.GetString("apagarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Postagem.
        /// </summary>
        public static string apagarPostagem {
            get {
                return ResourceManager.GetString("apagarPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Reserva de Ambiente.
        /// </summary>
        public static string apagarReservaAmbiente {
            get {
                return ResourceManager.GetString("apagarReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Veículo.
        /// </summary>
        public static string apagarVeiculo {
            get {
                return ResourceManager.GetString("apagarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apargar Condomínio.
        /// </summary>
        public static string apargarCondominio {
            get {
                return ResourceManager.GetString("apargarCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apagar Registro de Ocorrência.
        /// </summary>
        public static string apargarRegistroOcorrencia {
            get {
                return ResourceManager.GetString("apargarRegistroOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área Pública.
        /// </summary>
        public static string areaPublica {
            get {
                return ResourceManager.GetString("areaPublica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string bairro {
            get {
                return ResourceManager.GetString("bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloco.
        /// </summary>
        public static string bloco {
            get {
                return ResourceManager.GetString("bloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocos.
        /// </summary>
        public static string blocos {
            get {
                return ResourceManager.GetString("blocos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP.
        /// </summary>
        public static string cep {
            get {
                return ResourceManager.GetString("cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string cidade {
            get {
                return ResourceManager.GetString("cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string complemento {
            get {
                return ResourceManager.GetString("complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condomínio.
        /// </summary>
        public static string condominio {
            get {
                return ResourceManager.GetString("condominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condomínios.
        /// </summary>
        public static string condominios {
            get {
                return ResourceManager.GetString("condominios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar esta Administradora?.
        /// </summary>
        public static string confirmacaoApagarAdministradora {
            get {
                return ResourceManager.GetString("confirmacaoApagarAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você realmente deseja apagar essa enquete?.
        /// </summary>
        public static string confirmacaoApagarEnquete {
            get {
                return ResourceManager.GetString("confirmacaoApagarEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente Apagar Moradia.
        /// </summary>
        public static string confirmacaoApagarMoradia {
            get {
                return ResourceManager.GetString("confirmacaoApagarMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar esta pessoa?.
        /// </summary>
        public static string confirmacaoApagarPessoa {
            get {
                return ResourceManager.GetString("confirmacaoApagarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja cancelar esta reserva?.
        /// </summary>
        public static string confirmacaoApagarReserva {
            get {
                return ResourceManager.GetString("confirmacaoApagarReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este veículo?.
        /// </summary>
        public static string confirmacaoApagarVeiculo {
            get {
                return ResourceManager.GetString("confirmacaoApagarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este bloco?.
        /// </summary>
        public static string confirmacaoBloco {
            get {
                return ResourceManager.GetString("confirmacaoBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja apagar este condominio?.
        /// </summary>
        public static string confirmacaoCondominio {
            get {
                return ResourceManager.GetString("confirmacaoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmaNovaSenha.
        /// </summary>
        public static string confirmaNovaSenha {
            get {
                return ResourceManager.GetString("confirmaNovaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirma Senha.
        /// </summary>
        public static string confirmaSenha {
            get {
                return ResourceManager.GetString("confirmaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cor.
        /// </summary>
        public static string cor {
            get {
                return ResourceManager.GetString("cor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string cpf {
            get {
                return ResourceManager.GetString("cpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criador.
        /// </summary>
        public static string criador {
            get {
                return ResourceManager.GetString("criador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Publicação Automática.
        /// </summary>
        public static string dataAutomatica {
            get {
                return ResourceManager.GetString("dataAutomatica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Entrada.
        /// </summary>
        public static string dataEntrada {
            get {
                return ResourceManager.GetString("dataEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Exclusão Automática.
        /// </summary>
        public static string dataExclusao {
            get {
                return ResourceManager.GetString("dataExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Finalização.
        /// </summary>
        public static string dataFim {
            get {
                return ResourceManager.GetString("dataFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de fechamento da enquete.
        /// </summary>
        public static string dataFimEnquete {
            get {
                return ResourceManager.GetString("dataFimEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Início.
        /// </summary>
        public static string dataInicio {
            get {
                return ResourceManager.GetString("dataInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de abertura da enquete.
        /// </summary>
        public static string dataInicioEnquete {
            get {
                return ResourceManager.GetString("dataInicioEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saida.
        /// </summary>
        public static string dataSaida {
            get {
                return ResourceManager.GetString("dataSaida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string descricao {
            get {
                return ResourceManager.GetString("descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string detalhes {
            get {
                return ResourceManager.GetString("detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes Administradora.
        /// </summary>
        public static string detalhesAdministradora {
            get {
                return ResourceManager.GetString("detalhesAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Bloco.
        /// </summary>
        public static string detalhesBloco {
            get {
                return ResourceManager.GetString("detalhesBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Condomínio.
        /// </summary>
        public static string detalhesCondominio {
            get {
                return ResourceManager.GetString("detalhesCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Enquete.
        /// </summary>
        public static string detalhesEnquete {
            get {
                return ResourceManager.GetString("detalhesEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes Pessoa.
        /// </summary>
        public static string detalhesPessoa {
            get {
                return ResourceManager.GetString("detalhesPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes da Reserva de Ambiente.
        /// </summary>
        public static string detalhesReservaAmbiente {
            get {
                return ResourceManager.GetString("detalhesReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes do Veículo.
        /// </summary>
        public static string detalhesVeiculo {
            get {
                return ResourceManager.GetString("detalhesVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Administradora.
        /// </summary>
        public static string editarAdministradora {
            get {
                return ResourceManager.GetString("editarAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Bloco.
        /// </summary>
        public static string editarBloco {
            get {
                return ResourceManager.GetString("editarBloco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Condomínio.
        /// </summary>
        public static string editarCondominio {
            get {
                return ResourceManager.GetString("editarCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar a Enquete.
        /// </summary>
        public static string editarEnquete {
            get {
                return ResourceManager.GetString("editarEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Pessoa.
        /// </summary>
        public static string editarPessoa {
            get {
                return ResourceManager.GetString("editarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Proprietário.
        /// </summary>
        public static string editarProprietario {
            get {
                return ResourceManager.GetString("editarProprietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Reserva de Ambiente.
        /// </summary>
        public static string editarReservaAmbiente {
            get {
                return ResourceManager.GetString("editarReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Veículo.
        /// </summary>
        public static string editarVeiculo {
            get {
                return ResourceManager.GetString("editarVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquete.
        /// </summary>
        public static string enquete {
            get {
                return ResourceManager.GetString("enquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes.
        /// </summary>
        public static string enquetes {
            get {
                return ResourceManager.GetString("enquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes Ativas.
        /// </summary>
        public static string enquetesAtivas {
            get {
                return ResourceManager.GetString("enquetesAtivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes em Andamento.
        /// </summary>
        public static string enquetesEmAndamento {
            get {
                return ResourceManager.GetString("enquetesEmAndamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquetes Finalizadas.
        /// </summary>
        public static string enquetesFinalizadas {
            get {
                return ResourceManager.GetString("enquetesFinalizadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Área Pública.
        /// </summary>
        public static string idArea {
            get {
                return ResourceManager.GetString("idArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do condomínio.
        /// </summary>
        public static string idCondominio {
            get {
                return ResourceManager.GetString("idCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Pessoa.
        /// </summary>
        public static string idPessoa {
            get {
                return ResourceManager.GetString("idPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do síndico.
        /// </summary>
        public static string idSindico {
            get {
                return ResourceManager.GetString("idSindico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Status Pagamento.
        /// </summary>
        public static string idStatusPagamento {
            get {
                return ResourceManager.GetString("idStatusPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Tipo Moradia.
        /// </summary>
        public static string idTipoMoradia {
            get {
                return ResourceManager.GetString("idTipoMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Veículo.
        /// </summary>
        public static string idVeiculo {
            get {
                return ResourceManager.GetString("idVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista das Áreas públicas.
        /// </summary>
        public static string listaAreasPublicas {
            get {
                return ResourceManager.GetString("listaAreasPublicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus Registros de Ocorrência.
        /// </summary>
        public static string listaRegistroOcorrencia {
            get {
                return ResourceManager.GetString("listaRegistroOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string local {
            get {
                return ResourceManager.GetString("local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenha-me conectado.
        /// </summary>
        public static string manterConectado {
            get {
                return ResourceManager.GetString("manterConectado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo.
        /// </summary>
        public static string modelo {
            get {
                return ResourceManager.GetString("modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moradia.
        /// </summary>
        public static string moradia {
            get {
                return ResourceManager.GetString("moradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Administradora.
        /// </summary>
        public static string novaAdministradora {
            get {
                return ResourceManager.GetString("novaAdministradora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Área Pública.
        /// </summary>
        public static string novaArea {
            get {
                return ResourceManager.GetString("novaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Enquete.
        /// </summary>
        public static string novaEnquete {
            get {
                return ResourceManager.GetString("novaEnquete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Moradia.
        /// </summary>
        public static string novaMoradia {
            get {
                return ResourceManager.GetString("novaMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Pessoa.
        /// </summary>
        public static string novaPessoa {
            get {
                return ResourceManager.GetString("novaPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Postagem.
        /// </summary>
        public static string novaPostagem {
            get {
                return ResourceManager.GetString("novaPostagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Reserva de Ambiente.
        /// </summary>
        public static string novaReservaAmbiente {
            get {
                return ResourceManager.GetString("novaReservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string novaSenha {
            get {
                return ResourceManager.GetString("novaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string novo {
            get {
                return ResourceManager.GetString("novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Condomínio.
        /// </summary>
        public static string novoCondominio {
            get {
                return ResourceManager.GetString("novoCondominio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Registro de Ocorrência.
        /// </summary>
        public static string novoRegistroOcorrencia {
            get {
                return ResourceManager.GetString("novoRegistroOcorrencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Veículo.
        /// </summary>
        public static string novoVeiculo {
            get {
                return ResourceManager.GetString("novoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está seguro que quer fazer isso?.
        /// </summary>
        public static string perguntaConfirmacao {
            get {
                return ResourceManager.GetString("perguntaConfirmacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoa.
        /// </summary>
        public static string pessoa {
            get {
                return ResourceManager.GetString("pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pessoas.
        /// </summary>
        public static string pessoas {
            get {
                return ResourceManager.GetString("pessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa.
        /// </summary>
        public static string placa {
            get {
                return ResourceManager.GetString("placa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postagens.
        /// </summary>
        public static string postagens {
            get {
                return ResourceManager.GetString("postagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predio.
        /// </summary>
        public static string predio {
            get {
                return ResourceManager.GetString("predio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprietário.
        /// </summary>
        public static string proprietario {
            get {
                return ResourceManager.GetString("proprietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Andares.
        /// </summary>
        public static string qtdeAndares {
            get {
                return ResourceManager.GetString("qtdeAndares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade de Moradias.
        /// </summary>
        public static string qtdeMoradias {
            get {
                return ResourceManager.GetString("qtdeMoradias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo é obrigatório!.
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserva de Ambiente.
        /// </summary>
        public static string reservaAmbiente {
            get {
                return ResourceManager.GetString("reservaAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservas de Ambiente.
        /// </summary>
        public static string reservasAmbiente {
            get {
                return ResourceManager.GetString("reservasAmbiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RG.
        /// </summary>
        public static string rg {
            get {
                return ResourceManager.GetString("rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua.
        /// </summary>
        public static string rua {
            get {
                return ResourceManager.GetString("rua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string salvar {
            get {
                return ResourceManager.GetString("salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string selecione {
            get {
                return ResourceManager.GetString("selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha Atual.
        /// </summary>
        public static string senhaAtual {
            get {
                return ResourceManager.GetString("senhaAtual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Síndico.
        /// </summary>
        public static string sindico {
            get {
                return ResourceManager.GetString("sindico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status do Pagamento.
        /// </summary>
        public static string statusPagamento {
            get {
                return ResourceManager.GetString("statusPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        public static string tamanho {
            get {
                return ResourceManager.GetString("tamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone Celular.
        /// </summary>
        public static string telefoneCelular {
            get {
                return ResourceManager.GetString("telefoneCelular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone Fixo.
        /// </summary>
        public static string telefoneFixo {
            get {
                return ResourceManager.GetString("telefoneFixo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        public static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Moradia.
        /// </summary>
        public static string tipoMoradia {
            get {
                return ResourceManager.GetString("tipoMoradia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo do veículo.
        /// </summary>
        public static string tipoVeiculo {
            get {
                return ResourceManager.GetString("tipoVeiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas Enquetes.
        /// </summary>
        public static string todasEnquetes {
            get {
                return ResourceManager.GetString("todasEnquetes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Pagamento.
        /// </summary>
        public static string valorPagamento {
            get {
                return ResourceManager.GetString("valorPagamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículo.
        /// </summary>
        public static string veiculo {
            get {
                return ResourceManager.GetString("veiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veículos.
        /// </summary>
        public static string veiculos {
            get {
                return ResourceManager.GetString("veiculos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string voltar {
            get {
                return ResourceManager.GetString("voltar", resourceCulture);
            }
        }
    }
}
