//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Atendimento.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Atendimento {
	public Object SolicitanteAtendimento;
	public Object TituloAtendimento;
	public Object DescricaoAtendimento;
	public Object EstadoAtendimento;
}
