//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Condominio.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Condominio {
	public Object Sindico;
	public Object NomeCondominio;
	public Object Endereco;
}
