//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaFuncionario.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaFuncionario {
	public void NovoFuncionario() {
	
	}
	
	public void VisualizarDadosFuncionario() {
	
	}
	
	public void EditarDadosFuncionario() {
	
	}
	
	public void ExcluirFuncionario() {
	
	}
	
	public void SalvarDadosFuncionario() {
	
	}
	
	public void PontuarFuncionario() {
	
	}
}
