//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarAcesso.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarAcesso {
	public void NovaPessoa() {
	
	}
	
	public void EditarDadosPessoa() {
	
	}
	
	public void ExcluirPessoa() {
	
	}
}
