//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarEspacos.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarEspacos {
	public void AlterarStatusAreaPublica() {
	
	}
	
	public void NovaAreaPublica() {
	
	}
	
	public void NovaMoradia() {
	
	}
	
	public void NovoBloco() {
	
	}
	
	public void VisualisarDadosBloco() {
	
	}
	
	public void EditarDadosBloco() {
	
	}
	
	public void ExcluirBloco() {
	
	}
}
