//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorCentralDeAtendimento.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorCentralDeAtendimento {
	public void ResponderMensagem() {
	
	}
	
	public void EnviarEmail() {
	
	}
	
	public void AnalisarTextoEmail() {
	
	}
	
	public void ExibirPerguntaseRespostasFrequentes() {
	
	}
	
	public void BuscarPerResFrequentes() {
	
	}
	
	public void VisualizarRespostaRapida() {
	
	}
	
	public void VisualizarEmail() {
	
	}
	
	public void VisualizarMensagem() {
	
	}
}
