//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaPessoa.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaPessoa {
	public void NovaPessoa() {
	
	}
	
	public void EditarDadosPessoa() {
	
	}
	
	public void ExcluirPessoa() {
	
	}
	
	public void SalavarDadosPessoa() {
	
	}
	
	public void PesquisarCodigo() {
	
	}
	
	public void RegistrarEntrada() {
	
	}
}
