//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pessoa.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class Pessoa {
	public Object NomePessoa;
	public Object RGpessoa;
	public Object CPFpessoa;
	public Object SexoPessoa;
	public Object EmailPessoa;
	public Object LoginPessoa;
	public Object SenhaPessoa;
	public Object TelFixo;
	public Object TelCel;
	public Object TipoPessoa;
	public Object CodigoPessoa;
}
