//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaPontuarFuncionarios.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaPontuarFuncionarios {
	public void PontuarFuncionario() {
	
	}
}
