//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AreaPublica.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class AreaPublica {
	public Object NomeAreaPublica;
	public Object LocalMoradia;
	public Object TamanhoMoradia;
	public Object ValorDoPagamento;
	public Object EstadoAreaPublica;
}
