//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ComentarioListaDeDiscussao.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ComentarioListaDeDiscussao {
	public Object Morador;
	public Object Lista;
	public Object Comentario;
}
