//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorFinanceiro.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class ControladorFinanceiro {
	public void BuscarMovimentacoesFinanceiras() {
	
	}
	
	public void AnalisarBusca() {
	
	}
	
	public void NovoPlanoDeConta() {
	
	}
	
	public void AnalisarDados() {
	
	}
	
	public void BuscarMovimentacoesFinanceiras() {
	
	}
	
	public void VisualizarDadosPlanoDeConta() {
	
	}
	
	public void EditarPlanoDeConta() {
	
	}
	
	public void ValidarDados() {
	
	}
	
	public void ExcluirPlanoDeConta() {
	
	}
	
	public void Autenticar() {
	
	}
	
	public void VisualizarHistoricoDeAlteracao() {
	
	}
}
