//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaAutenticacao.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaAutenticacao {
	public void ValidarLoginSenha(String login, String senha) {
	
	}
	
	public void EnviarLoginSenhaPorEmail() {
	
	}
}
