//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaSetor.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaSetor {
	public void NovoSetor() {
	
	}
	
	public void EditarDadosSetor() {
	
	}
	
	public void ExcluirSetor() {
	
	}
	
	public void SalvarDadosSetor() {
	
	}
}
