//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaListaDeDiscussao.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaListaDeDiscussao {
	public void NovaListaDiscussao() {
	
	}
	
	public void VisualizarListaDeDiscussao() {
	
	}
	
	public void ExcluirListaDeDiscussao() {
	
	}
	
	public void SalvarDadosListaDeDiscussao() {
	
	}
	
	public void PublicarComentario() {
	
	}
}
