//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : PersistenciaOcorrencia.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class PersistenciaOcorrencia {
	public void NovaOcorrencia() {
	
	}
	
	public void EnviarOcorrencia() {
	
	}
	
	public void VisualizarDadosOcorrencia() {
	
	}
	
	public void EditarDadosOcorrencia() {
	
	}
	
	public void ExcluirOcorrencia() {
	
	}
	
	public void SalvarDadosOcorrencia() {
	
	}
	
	public void SalvarStatusOcorrencia() {
	
	}
}
