//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciamentoFinanceiro.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciamentoFinanceiro {
	public void ReceberTipoDeContaEIntervaloDatas() {
	
	}
	
	public void ExibeMovimentacaoDoMes() {
	
	}
	
	public void NovoPlanoDeConta() {
	
	}
	
	public void ExibeMovimentacaoDoMes() {
	
	}
	
	public void TipoDeContaEIntervaloDatas() {
	
	}
	
	public void VisualizarDadosPlanoDeConta() {
	
	}
	
	public void EditarPlanoDeConta() {
	
	}
	
	public void ExcluirPlanoDeConta() {
	
	}
	
	public void VisualizarHistoricoDeAlteracao() {
	
	}
	
	public void AnalisarMovimentacaoNoPeriodo() {
	
	}
}
