//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TelaGerenciarOcorrencias.java
//  @ Date : 08/04/2013
//  @ Author : 
//
//




public class TelaGerenciarOcorrencias {
	public void VisualizarOcorrencias() {
	
	}
	
	public void NovoTipoOcorrencia() {
	
	}
}
